"""Trade lexicon: abbreviation expansions, buyer-side synonyms, and the refusal list.

Three tables with three different jobs.

ABBREVIATIONS  expansions safe enough to publish, each tagged with why it is safe.
TRADE_SYNONYMS the words a buyer types that a supplier never writes. Used only to build
               evaluation queries and SEARCH_KEYWORDS - never to invent an attribute.
AMBIGUOUS      abbreviations we refuse to expand without a document that says so. "DKO"
               lives here until a manufacturer page proves its meaning.
"""
from __future__ import annotations

# abbreviation -> (expansion, scope) ; scope explains why the expansion is safe
ABBREVIATIONS: dict[str, tuple[str, str]] = {
    "cplg": ("Coupling", "universal plumbing abbreviation"),
    "brs": ("Brass", "universal material abbreviation"),
    "ss": ("Stainless Steel", "universal material abbreviation"),
    "sst": ("Stainless Steel", "universal material abbreviation"),
    "galv": ("Galvanized", "universal finish abbreviation"),
    "gal": ("Gallon", "approved UOM"),
    "blk": ("Black", "universal colour abbreviation"),
    "cs": ("Carbon Steel", "material abbreviation, category-scoped"),
    "cu": ("Copper", "universal material abbreviation"),
    "pvc": ("PVC", "material designation"),
    "cpvc": ("CPVC", "material designation"),
    "abs": ("ABS", "material designation"),
    "pex": ("PEX", "material designation"),
    "mip": ("Male Iron Pipe", "standard end connection"),
    "fip": ("Female Iron Pipe", "standard end connection"),
    "mpt": ("Male Pipe Thread", "standard end connection"),
    "fpt": ("Female Pipe Thread", "standard end connection"),
    "npt": ("National Pipe Thread", "approved thread standard"),
    "swt": ("Sweat", "standard end connection"),
    "cxc": ("Copper x Copper", "standard end connection"),
    "cxm": ("Copper x Male", "standard end connection"),
    "slip": ("Slip", "standard end connection"),
    "sch": ("Schedule", "pipe schedule designator"),
    "dwv": ("Drain Waste Vent", "standard plumbing service class"),
    "elb": ("Elbow", "universal fitting abbreviation"),
    "nip": ("Nipple", "universal fitting abbreviation"),
    "bv": ("Ball Valve", "universal valve abbreviation"),
    "gv": ("Gate Valve", "universal valve abbreviation"),
    "cv": ("Check Valve", "universal valve abbreviation"),
    "wh": ("Water Heater", "category-scoped abbreviation"),
    "dw": ("Dishwasher", "category-scoped abbreviation"),
    "hd": ("Heavy Duty", "universal grade abbreviation"),
    "std": ("Standard", "universal grade abbreviation"),
    "lt": ("Light", "universal grade abbreviation"),
    "asy": ("Assembly", "universal abbreviation"),
    "assy": ("Assembly", "universal abbreviation"),
    "cb": ("Circuit Breaker", "category-scoped abbreviation"),
    "gfci": ("GFCI", "standard device designation"),
    "afci": ("AFCI", "standard device designation"),
    "emt": ("EMT", "standard conduit designation"),
    "thhn": ("THHN", "standard wire insulation designation"),
    "nm-b": ("NM-B", "standard cable designation"),
    "tstat": ("Thermostat", "category-scoped abbreviation"),
    "cond": ("Condensing", "category-scoped abbreviation"),
    "recep": ("Receptacle", "category-scoped abbreviation"),
    "recpt": ("Receptacle", "category-scoped abbreviation"),
    "hex": ("Hex", "universal head/drive abbreviation"),
    "phil": ("Phillips", "universal drive abbreviation"),
    "sq": ("Square", "universal drive abbreviation"),
    "hh": ("Hex Head", "universal head abbreviation"),
    "fh": ("Flat Head", "universal head abbreviation"),
    "ph": ("Pan Head", "universal head abbreviation"),
    "zp": ("Zinc Plated", "universal finish abbreviation"),
    "yz": ("Yellow Zinc", "universal finish abbreviation"),
    "grd": ("Grade", "universal abbreviation"),
    "mtl": ("Metal", "universal material abbreviation"),
    "alum": ("Aluminum", "universal material abbreviation"),
    "wht": ("White", "universal colour abbreviation"),
    "brn": ("Brown", "universal colour abbreviation"),
    "gry": ("Grey", "universal colour abbreviation"),
    "chr": ("Chrome", "universal finish abbreviation"),
    "pc": ("Polished Chrome", "finish abbreviation, category-scoped"),
    "bn": ("Brushed Nickel", "finish abbreviation, category-scoped"),
    "orb": ("Oil Rubbed Bronze", "finish abbreviation, category-scoped"),
    "mb": ("Matte Black", "finish abbreviation, category-scoped"),
    "merv": ("MERV", "standard filter rating designation"),
    "nrr": ("Noise Reduction Rating", "standard PPE designation"),
    "led": ("LED", "standard lamp designation"),
    "ansi": ("ANSI", "standards body"),
    "astm": ("ASTM", "standards body"),
    "nsf": ("NSF", "standards body"),
    "ul": ("UL", "standards body"),
    "csa": ("CSA", "standards body"),
}

# Abbreviations that look expandable but are not, absent a manufacturer source.
# Each is left verbatim in the output and counted in the abstention metric.
AMBIGUOUS: dict[str, str] = {
    "dko": "arbor/knockout designation - no seed source confirms the expansion",
    "ftg": "fitting OR footage, depends on category",
    "cc": "compression x compression OR cubic centimetre",
    "ips": "iron pipe size OR iron pipe straight",
    "od": "outside diameter OR overdrive, category dependent",
    "id": "inside diameter OR identification",
    "lp": "liquid propane OR low pressure",
    "ng": "natural gas OR no good",
    "rh": "right hand OR relative humidity",
    "lh": "left hand OR low heat",
    "sp": "static pressure OR special OR single pole",
    "tp": "type OR total pressure OR twisted pair",
    "cw": "cold water OR clockwise",
    "hw": "hot water OR hardware",
    "xh": "extra heavy OR cross head",
    "fs": "full size OR flat shank OR field service",
    "tc": "thermocouple OR tungsten carbide",
    "mc": "metal clad OR machine cut",
    "wc": "water closet OR water column",
    "pt": "pint OR pressure treated OR pipe thread",
}

# canonical item type -> the words a buyer actually types.
# These build the vocabulary-gap query set; a query only counts if the term does NOT
# appear anywhere in the raw supplier text.
TRADE_SYNONYMS: dict[str, list[str]] = {
    "Cut-Off Wheels": ["cut-off wheel", "abrasive wheel", "chop saw wheel", "thin cutting wheel",
                       "metal cutting disc", "type 1 wheel"],
    "Grinding Wheels": ["grinding wheel", "depressed center wheel", "type 27 wheel",
                        "metal grinding disc"],
    "Sanding Discs": ["abrasive disc", "sanding disc", "psa disc", "film backed disc",
                      "orbital sander disc"],
    "Flap Discs": ["flap disc", "abrasive flap wheel", "blending disc"],
    "Drill Bits": ["drill bit", "twist drill", "jobber bit", "metal drilling bit"],
    "Saw Blades": ["saw blade", "circular blade", "recip blade", "metal cutting blade"],
    "Couplings": ["pipe coupling", "coupler", "slip fitting", "pipe joiner"],
    "Elbows": ["pipe elbow", "ell fitting", "90 degree fitting", "45 degree fitting"],
    "Tees": ["pipe tee", "three way fitting", "branch fitting"],
    "Nipples": ["pipe nipple", "threaded nipple", "pipe stub"],
    "Adapters": ["pipe adapter", "transition fitting", "reducer bushing"],
    "Unions": ["pipe union", "dielectric union", "disconnect fitting"],
    "Ball Valves": ["ball valve", "shutoff valve", "isolation valve", "quarter turn valve"],
    "Gate Valves": ["gate valve", "wedge valve", "rising stem valve"],
    "Check Valves": ["check valve", "backflow valve", "one way valve"],
    "Kitchen Sink Faucets": ["kitchen faucet", "pull down sprayer faucet", "single handle faucet",
                             "high arc faucet"],
    "Bath Sink Faucets": ["lavatory faucet", "bathroom sink faucet", "widespread faucet",
                          "centerset faucet"],
    "Commercial Faucets": ["commercial faucet", "pre-rinse unit", "metering faucet",
                           "service sink faucet"],
    "Built-In Dishwashers": ["built-in dishwasher", "under counter dishwasher",
                             "stainless dishwasher", "quiet dishwasher"],
    "Ranges": ["kitchen range", "slide in range", "gas range", "electric range"],
    "Refrigerators": ["refrigerator", "french door fridge", "counter depth refrigerator"],
    "Washers": ["clothes washer", "front load washer", "high efficiency washer"],
    "Electric Water Heaters": ["electric water heater", "electric hot water tank",
                               "residential water heater"],
    "Gas Water Heaters": ["gas water heater", "natural gas hot water tank",
                          "atmospheric vent water heater"],
    "Condensing Units": ["condensing unit", "ac condenser", "outdoor condenser",
                         "split system condenser"],
    "Grilles & Registers": ["return air grille", "supply register", "ceiling diffuser"],
    "Thermostats": ["thermostat", "programmable thermostat", "heat pump thermostat"],
    "Air Filters": ["furnace filter", "pleated air filter", "hvac filter", "media filter"],
    "Circuit Breakers": ["circuit breaker", "load center breaker", "plug on breaker"],
    "Fuses": ["cartridge fuse", "time delay fuse", "class j fuse", "current limiting fuse"],
    "Receptacles": ["electrical outlet", "duplex receptacle", "gfci outlet",
                    "tamper resistant outlet"],
    "Switches": ["light switch", "toggle switch", "single pole switch", "dimmer switch"],
    "Junction Boxes": ["junction box", "electrical box", "device box", "old work box"],
    "Conduit Fittings": ["conduit connector", "emt connector", "compression coupling"],
    "Building Wire": ["building wire", "thhn wire", "romex cable", "nm-b cable"],
    "LED Lamps": ["led bulb", "a19 led lamp", "led retrofit lamp", "dimmable led"],
    "Ball Bearings": ["ball bearing", "deep groove bearing", "sealed bearing"],
    "AC Motors": ["electric motor", "three phase motor", "tefc motor", "induction motor"],
    "V-Belts": ["v-belt", "drive belt", "cogged v belt"],
    "Composite Decking Boards": ["composite decking", "capped composite deck board",
                                 "grooved deck board", "pvc deck board"],
    "Deck Railing": ["deck railing", "composite railing", "rail kit"],
    "Screws": ["deck screw", "self drilling screw", "wood screw", "structural screw"],
    "Anchors": ["concrete anchor", "wedge anchor", "sleeve anchor", "masonry anchor"],
    "Safety Glasses": ["safety glasses", "protective eyewear", "anti fog safety glasses"],
    "Work Gloves": ["work gloves", "cut resistant gloves", "coated work gloves"],
    "Hearing Protection": ["ear muffs", "hearing protector", "ear plugs"],
    "Thread Sealants": ["thread sealant", "pipe thread compound", "threadlocker",
                        "pipe dope"],
    "Penetrating Oils": ["penetrating oil", "rust penetrant", "spray lubricant"],
    "Spray Paint": ["spray paint", "aerosol enamel", "rust preventive spray"],
}

# Hand-written trade queries used for the MRR@10 measurement. Deliberately written the
# way a counter clerk types, not the way the catalogue is written.
TRADE_QUERIES: list[tuple[str, str]] = [
    ("5 inch thin cut off wheel 7/8 arbor", "Cut-Off Wheels"),
    ("p120 stikit film disc 6 inch", "Sanding Discs"),
    ("stainless dishwasher 24 inch built in", "Built-In Dishwashers"),
    ("1/2 brass slip coupling 150 psi", "Couplings"),
    ("composite deck board grooved brownstone", "Composite Decking Boards"),
    ("20 amp gfci tamper resistant outlet white", "Receptacles"),
    ("merv 13 pleated furnace filter 20x25x1", "Air Filters"),
    ("50 gallon electric water heater 240v", "Electric Water Heaters"),
    ("kitchen faucet pull down single handle brushed nickel", "Kitchen Sink Faucets"),
    ("3 ton condenser 16 seer", "Condensing Units"),
    ("1 hp three phase tefc motor 1750 rpm", "AC Motors"),
    ("12 awg thhn stranded copper wire", "Building Wire"),
    ("20 amp single pole plug on breaker", "Circuit Breakers"),
    ("cut resistant gloves level a4 large", "Work Gloves"),
    ("blue thread sealant 50 ml", "Thread Sealants"),
    ("3/4 inch brass ball valve full port npt", "Ball Valves"),
    ("dimmable a19 led lamp 2700k 800 lumens", "LED Lamps"),
    ("2-1/2 inch deck screw tan 5 lb", "Screws"),
    ("4-1/2 inch flap disc 60 grit type 29", "Flap Discs"),
    ("programmable thermostat 2 stage heat", "Thermostats"),
]


def expansions() -> dict[str, str]:
    return {k: v[0] for k, v in ABBREVIATIONS.items()}
